package com.uor.group_14.touripearl_backend.entity.enumEntity;

public enum Interests {
    ADVENTURE_TRAVEL, CULTURAL_EXPERIENCES, BEACH_GETAWAYS, CITY_TOURS, HISTORICAL_SITES, NATURE_WILDLIFE,
    LUXURY_TRAVEL, PHOTOGRAPHY, HIKING, LOCAL_CUISINE, CULTURAL_SITES
}
