package com.uor.group_14.touripearl_backend.entity.enumEntity;

public enum LanguageName {
    AFRIKAANS, ALBANIAN, AMHARIC, ARABIC, ARMENIAN, ASSAMESE, AZERBAIJANI, BASQUE,
    BELARUSIAN, BENGALI, BOSNIAN, BULGARIAN, CATALAN, CEBUANO, CHICHEWA, CHINESE ,
    CORSICAN, CROATIAN, CZECH, DANISH, DUTCH, ENGLISH, ESPERANTO, ESTONIAN, FILIPINO,
    FINNISH, FRENCH, FRISIAN, GALICIAN, GEORGIAN, GERMAN, GREEK, GUJARATI, HAUSA,
    HAWAIIAN, HEBREW, HINDI, HMONG, HUNGARIAN, ICELANDIC, IGBO, INDONESIAN, IRISH,
    ITALIAN, JAPANESE, JAVANESE, KANNADA, KAZAKH, KHMER, KINYARWANDA, KOREAN, KURDISH,
    KYRGYZ, LAO, LATIN, LATVIAN, LITHUANIAN, LUXEMBOURGISH, MACEDONIAN, MALAGASY, MALAY,
    MALAYALAM, MALTESE, MAORI, MARATHI, MONGOLIAN, NEPALI, NORWEGIAN, ODIA, PASHTO, PERSIAN,
    POLISH, PORTUGUESE, PUNJABI, ROMANIAN, RUSSIAN, SAMOAN, SERBIAN, SESOTHO, SHONA,
    SINDHI, SINHALA, SLOVAK, SLOVENIAN, SOMALI, SPANISH, SUNDANESE, SWAHILI, SWEDISH,
    TAJIK, TAMIL, TATAR, TELUGU, THAI, TURKISH, TURKMEN, UKRAINIAN, URDU, UYGHUR, UZBEK,
    VIETNAMESE, WELSH, XHOSA, YIDDISH, YORUBA, ZULU
}
